# Generated by Django 3.2 on 2021-04-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaPayment',
            new_name='Mpesa_Payments',
        ),
    ]
